### ISSUE TITLE
rebar3_eqc.erl:12: can't find include lib "eqc/include/eqc.hrl"

### ISSUE THREAD

**Issue by kstarikov** [kellymclaughlin/rebar3-eqc-plugin#14]
``` zsh
➜  rebar3_eqc git:(d1895b4) ✗ rebar3 compile
===> Verifying dependencies...
===> Compiling rebar3_eqc
===> Compiling rebar3_eqc/src/rebar3_eqc.erl failed
rebar3_eqc/src/rebar3_eqc.erl:12: can't find include lib "eqc/include/eqc.hrl"

rebar3_eqc/src/rebar3_eqc.erl:156: function on_output/2 undefined
rebar3_eqc/src/rebar3_eqc.erl:165: function on_output/2 undefined
```

**Comment by kellymclaughlin** [comment]
It looks like you don't have eqc properly installed such that it is on the erlang code path. Are you using the full version of eqc or the eqc mini? At least with the full version there is an `eqc_install.beam` file included that can be used to set it up for you or you can manually ensure that your erlang installation can find the eqc files. That should take care of the issue.
