### ISSUE TITLE
Ignore nonapplicable files when listing eqc directory contents

### ISSUE THREAD

**Issue by kellymclaughlin** [kellymclaughlin/rebar3-eqc-plugin#3]
Ignore files such as vim swap files or other nonapplicable files that may be present.

Example of failure:

```
{undef,[{'.myapp_eqc_statem.erl',module_info,[exports],[]}, 
```

**Comment by Licenser** [comment]
The same happens with header files

**Comment by kellymclaughlin** [comment]
> The same happens with header files

Thanks for the report. I'll try get this fixed in the next few days and push out a new version.

**Comment by kellymclaughlin** [comment]
I've pushed a `0.0.6` tag with a fix for this and published an updated package to Hex as well.
